from lexer import LexicalAnalyzer
from syntactic import SyntacticAnalyzer
from semantic import SemanticAnalyzer

# Load the test input from a file
with open("story.txt", "r", encoding="utf-8") as f:
    code = f.read()

# Run the lexical analysis
lexer = LexicalAnalyzer()
tokens = lexer.lex(code)
print("Tokens generated by lexer:")
for token in tokens:
    print(token)

# Run the syntactic analysis
print("\nStarting syntactic analysis...")
syntactic = SyntacticAnalyzer(tokens)
syntactic.parse()
print("Parsing completed successfully!")

# Run the semantic analysis
print("\nStarting semantic analysis...")
semantic = SemanticAnalyzer(tokens)
story_structure = semantic.analyze()
print("Semantic analysis completed successfully!")

print("\nStory structure:")
import pprint
pprint.pprint(story_structure)
